example:
  property: I AM THE DEFAULT
encrypted: #'Giovanni' cifrato
  property: {cipher}e7a4180f07a0e883db8b3ecda5cf246e1ba3d3ac9556b30b9e48c1eb8c350cf3
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eagle_eye_local
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          time_zone: TimeZone